<?php

namespace Larahammer\Generator\Commands;

use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Str;

class DeleteCommand extends Command
{
    protected $signature = 'larahammer:delete
                            {name : Model name to delete (e.g. Product)}
                            {--force : Skip confirmation prompt}';

    protected $description = 'Delete all files generated by larahammer:make for a given model.';

    protected Filesystem $files;

    public function __construct()
    {
        parent::__construct();
        $this->files = new Filesystem();
    }

    public function handle(): int
    {
        $name    = Str::studly($this->argument('name'));
        $table   = Str::snake(Str::plural($name));
        $route   = Str::kebab(Str::plural($name));
        $varName = Str::camel($name);

        $filesToDelete = $this->resolveFiles($name, $table, $route);

        $this->info("🗑️  Larahammer Delete — removing <fg=cyan>{$name}</> CRUD");
        $this->newLine();

        // Show what will be deleted
        $this->line('<fg=yellow>Files to be deleted:</>');
        foreach ($filesToDelete as $label => $path) {
            $exists = $this->fileOrDirExists($path);
            $icon   = $exists ? '<fg=red>✗</>' : '<fg=gray>-</>';
            $status = $exists ? '' : ' <fg=gray>(not found)</>';
            $this->line("  {$icon} {$label}{$status}");
        }

        $this->newLine();

        // Confirm
        if (!$this->option('force')) {
            if (!$this->confirm("Are you sure you want to delete all <fg=cyan>{$name}</> files?", false)) {
                $this->info('Cancelled.');
                return self::SUCCESS;
            }
        }

        $this->newLine();

        // Delete files
        foreach ($filesToDelete as $label => $path) {
            $this->runDelete($label, $path);
        }

        // Remove routes
        $this->runStep('Remove web routes', fn() => $this->removeRoutes($name, $route, 'web'));
        $this->runStep('Remove api routes', fn() => $this->removeRoutes($name, $route, 'api'));

        $this->newLine();
        $this->info("✅  Done! All <fg=cyan>{$name}</> files deleted.");
        $this->line('<fg=yellow>Remember:</> Run <fg=cyan>php artisan migrate:rollback</> if you want to drop the table too.');
        $this->newLine();

        return self::SUCCESS;
    }

    private function resolveFiles(string $name, string $table, string $route): array
    {
        return [
            // Core
            "Model"              => app_path("Models/{$name}.php"),
            "Controller (Blade)" => app_path("Http/Controllers/{$name}Controller.php"),
            "Controller (API)"   => app_path("Http/Controllers/Api/{$name}Controller.php"),
            "Request"            => app_path("Http/Requests/{$name}Request.php"),
            "API Resource"       => app_path("Http/Resources/{$name}Resource.php"),
            "Policy"             => app_path("Policies/{$name}Policy.php"),
            "Observer"           => app_path("Observers/{$name}Observer.php"),
            "Factory"            => database_path("factories/{$name}Factory.php"),
            "Seeder"             => database_path("seeders/{$name}Seeder.php"),
            "Views directory"    => resource_path("views/{$route}"),
            // Filament
            "Filament Resource"  => app_path("Filament/Resources/{$name}Resource.php"),
            "Filament Pages dir" => app_path("Filament/Resources/{$name}Resource/Pages"),
            // Tests
            "Feature Test"       => base_path("tests/Feature/{$name}CrudTest.php"),
            "Unit Test"          => base_path("tests/Unit/{$name}Test.php"),
        ];
    }

    private function runDelete(string $label, string $path): void
    {
        try {
            if (!$this->fileOrDirExists($path)) {
                return;
            }

            if ($this->files->isDirectory($path)) {
                $this->files->deleteDirectory($path);
            } else {
                $this->files->delete($path);
            }

            $this->line("  <fg=green>✓</> Deleted {$label}");
        } catch (\Exception $e) {
            $this->line("  <fg=red>✗</> {$label} — <fg=red>{$e->getMessage()}</>");
        }
    }

    private function removeRoutes(string $name, string $route, string $type): string
    {
        $routeFile = base_path("routes/{$type}.php");

        if (!$this->files->exists($routeFile)) {
            return "{$type}.php not found";
        }

        $content = $this->files->get($routeFile);

        // Remove web resource route
        $content = preg_replace(
            "/\nRoute::resource\('{$route}',[^\)]+\);/",
            '',
            $content
        );

        // Remove api resource route
        $content = preg_replace(
            "/\nRoute::apiResource\('{$route}',[^\)]+\);/",
            '',
            $content
        );

        $this->files->put($routeFile, $content);

        return "routes/{$type}.php cleaned";
    }

    private function fileOrDirExists(string $path): bool
    {
        return $this->files->exists($path) || $this->files->isDirectory($path);
    }

    private function runStep(string $label, callable $fn): void
    {
        try {
            $result = $fn();
            $this->line("  <fg=green>✓</> {$label}" . ($result ? " → <fg=gray>{$result}</>" : ''));
        } catch (\Exception $e) {
            $this->line("  <fg=red>✗</> {$label} — <fg=red>{$e->getMessage()}</>");
        }
    }
}